figure(10000)
NeuroGPUInit;
StimOut =  fullfile(BaseP,'Data','StimF.dat');
AllStim = nrn_mread(StimFN,Nt);
plot(AllStim');
AllStim = reshape(AllStim',size(AllStim,1)*size(AllStim,2),1);
Alldts =  nrn_mread(TimeFN,Nt);
dtchanges = [0 find(diff(Alldts))];
dts= Alldts(dtchanges+1);
fid = fopen(StimOut,'w');
fwrite(fid, length(AllStim)/Nt,'uint16');
fwrite(fid,Nt,'uint16');
fwrite(fid,Stim.comp,'uint16');
fwrite(fid,Stim.loc,'uint16');
fwrite(fid,Stim.area,FTYPESTR);
fwrite(fid,length(dtchanges),'uint16');
fwrite(fid,dtchanges,'uint16');
fwrite(fid,dts,FTYPESTR);
fwrite(fid,AllStim,FTYPESTR);
fclose(fid);