function [varsPerModelPerSeg, varsPerModelAllSeg,varsAllModelPerSeg] = na12_trates(varsPerModelPerSeg, varsPerModelAllSeg,varsAllModelPerSeg, constsPerModelPerSeg, constsPerModelAllSeg, constsAllModelAllSeg, v)
Def_ConstsPerModelPerSeg_na12;
Def_ConstsPerModelAllSegs_na12;
Def_VarsPerModelPerSeg_na12;
Def_VarsPerModelAllSegs_na12;
Def_VarsAllModelsPerSeg;
Def_ConstsAllModelsAllSegs;
[varsPerModelPerSeg, varsPerModelAllSeg,varsAllModelPerSeg] = na12_rates(varsPerModelPerSeg, varsPerModelAllSeg,varsAllModelPerSeg, constsPerModelPerSeg, constsPerModelAllSeg, constsAllModelAllSeg,v);

