function [varsPerModelPerSeg, varsPerModelAllSeg,varsAllModelPerSeg] = na16_trates(varsPerModelPerSeg, varsPerModelAllSeg,varsAllModelPerSeg, constsPerModelPerSeg, constsPerModelAllSeg, constsAllModelAllSeg, v)
Def_ConstsPerModelPerSeg_na16;
Def_ConstsPerModelAllSegs_na16;
Def_VarsPerModelPerSeg_na16;
Def_VarsPerModelAllSegs_na16;
Def_VarsAllModelsPerSeg;
Def_ConstsAllModelsAllSegs;
[varsPerModelPerSeg, varsPerModelAllSeg,varsAllModelPerSeg] = na16_rates(varsPerModelPerSeg, varsPerModelAllSeg,varsAllModelPerSeg, constsPerModelPerSeg, constsPerModelAllSeg, constsAllModelAllSeg,v);

